version: '3.3'
services:
  db:
    image: postgres:12-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword1
      POSTGRES_DB: tododb
    hostname: postgres
    restart: always
    user: root
    tty: true
    volumes:
      - ./pgsql:/var/lib/pgsql

  redis:
    image: redis:5.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
       - ./redis:/data

volumes:
  pgsql:
