<!doctype html>
<html class="no-js" lang="ja">

<head>
  <meta charset="utf-8">
  <title>${title}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/flatly/bootstrap.min.css">
</head>

<body>
  <h1>${title}</h1>
  <!-- Add your site or application content here -->
  <p>Hello world!</p>

  <script src="//ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</body>

</html>